export const checklistsConstants = {
  GET_CHECKLISTS_CATEGORIES_REQUEST: "GET_CHECKLISTS_CATEGORIES_REQUEST",
  GET_CHECKLISTS_CATEGORIES_SUCCESS: "GET_CHECKLISTS_CATEGORIES_SUCCESS",
  GET_CHECKLISTS_CATEGORIES_FAILURE: "GET_CHECKLISTS_CATEGORIES_FAILURE",

  GET_ICONS_REQUEST: "GET_ICONS_REQUEST",
  GET_ICONS_SUCCESS: "GET_ICONS_SUCCESS",
  GET_ICONS_FAILURE: "GET_ICONS_FAILURE",

  CHECK_USER_DAY_REQUEST: "CHECK_USER_DAY_REQUEST",
  CHECK_USER_DAY_SUCCESS: "CHECK_USER_DAY_SUCCESS",
  CHECK_USER_DAY_FAILURE: "CHECK_USER_DAY_FAILURE",

  CREATE_USER_CHECKLIST_REQUEST: "CREATE_USER_CHECKLIST_REQUEST",
  CREATE_USER_CHECKLIST_SUCCESS: "CREATE_USER_CHECKLIST_SUCCESS",
  CREATE_USER_CHECKLIST_FAILURE: "CREATE_USER_CHECKLIST_FAILURE",

  UPDATE_USER_CHECKLIST_REQUEST: "UPDATE_USER_CHECKLIST_REQUEST",
  UPDATE_USER_CHECKLIST_SUCCESS: "UPDATE_USER_CHECKLIST_SUCCESS",
  UPDATE_USER_CHECKLIST_FAILURE: "UPDATE_USER_CHECKLIST_FAILURE",

  DELETE_USER_CHECKLIST_REQUEST: "DELETE_USER_CHECKLIST_REQUEST",
  DELETE_USER_CHECKLIST_SUCCESS: "DELETE_USER_CHECKLIST_SUCCESS",
  DELETE_USER_CHECKLIST_FAILURE: "DELETE_USER_CHECKLIST_FAILURE",
};
